---
name: CD-dev
on:
    push:
        branches: [dev]

jobs:
    build-image:
        uses: ./.github/workflows/build-dev.yml
        with:
            image_tag: ${{ github.sha }}
        secrets: inherit

    deploy:
        runs-on: ubuntu-latest
        needs: [build-image]
        env:
            IMAGE_NAME: ${{ vars.DEV_IMAGE_NAME }}
            IMAGE_TAG: ${{ github.sha }}
            PROJECT_ID: ${{ secrets.DEV_GCP_PROJECT_ID }}
            ARTIFACT_REPOSITORY: ${{ vars.DEV_GCP_ARTIFACT_REPOSITORY }}
            REGION: ${{ vars.DEV_GCP_REGION }}
            INSTANCE_NAME: ${{ vars.DEV_INSTANCE_NAME }}

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: GCP Authentication
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.DEV_GCP_CREDENTIALS }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Execute Docker Command on GCP VM
              run: |
                  instances=$(gcloud compute instances list --filter="name~'-ai-'" --format="csv(name,zone)" | tail -n +2)

                  while IFS=',' read -r name zone; do
                      echo "Executing command on instance: $name in zone: $zone"
                      gcloud compute ssh "$name" \
                          --tunnel-through-iap \
                          --zone "$zone" \
                          --command "
                              set -e
                              gcloud auth configure-docker --quiet
                              gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

                              FILE_PATH='/etc/docker/model.pth'
                              # Explicit check with full path
                              if [ -f '/etc/docker/model.pth' ]; then
                                  echo \"File exists. Deleting...\"
                                  sudo rm '/etc/docker/model.pth'
                                  echo \"File deletion attempted.\"
                              else
                                  echo \"File does not exist.\"
                              fi
                              cd /etc/docker/
                              sudo gcloud storage cp gs://pbl6-dev-ai-model-bucket/model.pth .

                              sudo docker pull ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                              sudo docker compose -f /etc/docker/docker-compose.yml down
                              sudo yq e '.services."ai-service".image = \"${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}\"' -i /etc/docker/docker-compose.yml
                              sudo docker compose -f /etc/docker/docker-compose.yml up -d
                              sudo docker image prune --all -f
                              "
                  done <<<"$instances"
